### ISSUE TITLE
Spelling error in readme

### ISSUE THREAD

**Issue by adubinsky** [jaerodyne/covid19-data-ruby#1]
Could not find gem 'cov19_data_ruby' in git://github.com/jaerodyne/covid19-data-ruby.git (at master@54e3e75) or in gems cached in vendor/cache.
The source does not contain any versions of 'cov19_data_ruby'

The correct name of the gem from the .gemspec is:

  s.name        = 'covid19_data_ruby'

This it the readme that is wrong.
gem 'cov19_data_ruby'
And then execute:

$ bundle
Or install it yourself as:

$ gem install cov19_data_ruby

**Comment by jaerodyne** [comment]
@adubinsky oops, thanks for pointing that out! It's fixed now.
